### ISSUE TITLE
stormpy build error

### ISSUE THREAD

**Issue by eshitazaman** [stormchecker/stormpy#11]
I've installed all carl(master14 brach), pycarl and storm(master brach) successfully. when I tried building stormpy, I am getting following errors. Can you help me with this? I am attaching a screenshot of the error. I've tried different all the optional build commands but still getting the same error!
![Screen Shot 2020-02-07 at 12 32 29 AM](https://user-images.githubusercontent.com/45207632/74009060-06df6c80-4948-11ea-8ce0-90fad1e43247.png)

**Comment by sjunges** [comment]
The current stormpy [commit](https://github.com/moves-rwth/stormpy/commit/2ac480555452affe235eeb77b13458cc33eca035) and storm [commit](https://github.com/moves-rwth/storm/commit/0a6f54f33e07701fd606a23cc708a7202d70b936)  are in sync again. From what I get, you will need to pull only stormpy.  

This issue occurred as the latest version for storm (master) and stormpy (master) were not synched.  While we aim to avoid these issues, this sometimes happens -- sorry!

**Comment by eshitazaman** [comment]
Thank you so much. It is working now
