### ISSUE TITLE
stormpy build failed

### ISSUE THREAD

**Issue by bblwbtd** [stormchecker/stormpy#13]
I have installed storm and its dependencies successfully. But when I tried to build stormpy, it failed with the following logs. It seems like the compiler has something wrong, and I reinstalled g++ and gcc with homebrew, but it still didn't work. I tried to set CMAKE_C_COMPILER_ENV_VAR and CMAKE_C_COMPILER_ENV_VAR to gcc and g++, but nothing changed. I'm sure that my compiler is ok because I can use it to build other projects. Could you help me solve this?

ERROR: Command errored out with exit status 1:
     command: /Users/chenjienan/stormpy/env/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m7/8x1_4t2x7214c99gxx01xtkm0000gn/T/pip-install-ggd5q25s/pycarl/setup.py'"'"'; __file__='"'"'/private/var/folders/m7/8x1_4t2x7214c99gxx01xtkm0000gn/T/pip-install-ggd5q25s/pycarl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/m7/8x1_4t2x7214c99gxx01xtkm0000gn/T/pip-record-jdoz4rrp/install-record.txt --single-version-externally-managed --compile --install-headers /Users/chenjienan/stormpy/env/bin/../include/site/python3.7/pycarl
         cwd: /private/var/folders/m7/8x1_4t2x7214c99gxx01xtkm0000gn/T/pip-install-ggd5q25s/pycarl/
    Complete output (118 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/pycarl
    copying lib/pycarl/infinity.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl
    copying lib/pycarl/_version.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl
    copying lib/pycarl/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl
    copying lib/pycarl/_config.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl
    creating build/lib.macosx-10.14-x86_64-3.7/pycarl/gmp
    copying lib/pycarl/gmp/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/gmp
    creating build/lib.macosx-10.14-x86_64-3.7/pycarl/parse
    copying lib/pycarl/parse/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/parse
    copying lib/pycarl/parse/_config.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/parse
    creating build/lib.macosx-10.14-x86_64-3.7/pycarl/cln
    copying lib/pycarl/cln/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/cln
    copying lib/pycarl/cln/_config.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/cln
    creating build/lib.macosx-10.14-x86_64-3.7/pycarl/formula
    copying lib/pycarl/formula/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/formula
    creating build/lib.macosx-10.14-x86_64-3.7/pycarl/convert
    copying lib/pycarl/convert/cln_converter.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/convert
    copying lib/pycarl/convert/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/convert
    copying lib/pycarl/convert/gmp_converter.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/convert
    creating build/lib.macosx-10.14-x86_64-3.7/pycarl/gmp/parse
    copying lib/pycarl/gmp/parse/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/gmp/parse
    copying lib/pycarl/gmp/parse/_config.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/gmp/parse
    creating build/lib.macosx-10.14-x86_64-3.7/pycarl/gmp/formula
    copying lib/pycarl/gmp/formula/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/gmp/formula
    creating build/lib.macosx-10.14-x86_64-3.7/pycarl/cln/parse
    copying lib/pycarl/cln/parse/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/cln/parse
    copying lib/pycarl/cln/parse/_config.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/cln/parse
    creating build/lib.macosx-10.14-x86_64-3.7/pycarl/cln/formula
    copying lib/pycarl/cln/formula/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/cln/formula
    copying lib/pycarl/cln/formula/_config.py -> build/lib.macosx-10.14-x86_64-3.7/pycarl/cln/formula
    running egg_info
    writing lib/pycarl.egg-info/PKG-INFO
    writing dependency_links to lib/pycarl.egg-info/dependency_links.txt
    writing top-level names to lib/pycarl.egg-info/top_level.txt
    reading manifest file 'lib/pycarl.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'lib/pycarl.egg-info/SOURCES.txt'
    running build_ext
    CMake Error at /Users/chenjienan/omnetpp-5.5.1/tools/macosx/share/cmake/Modules/Compiler/AppleClang-DetermineCompiler.cmake:6 (string):
      string does not recognize sub-command APPEND
    Call Stack (most recent call first):
      /Users/chenjienan/omnetpp-5.5.1/tools/macosx/share/cmake/Modules/CMakeCompilerIdDetection.cmake:6 (include)
      /Users/chenjienan/omnetpp-5.5.1/tools/macosx/share/cmake/Modules/CMakeCompilerIdDetection.cmake:32 (_readFile)
      /Users/chenjienan/omnetpp-5.5.1/tools/macosx/share/cmake/Modules/CMakeDetermineCompilerId.cmake:128 (compiler_id_detection)
      /Users/chenjienan/omnetpp-5.5.1/tools/macosx/share/cmake/Modules/CMakeDetermineCompilerId.cmake:147 (CMAKE_DETERMINE_COMPILER_ID_WRITE)
      /Users/chenjienan/omnetpp-5.5.1/tools/macosx/share/cmake/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
      /Users/chenjienan/omnetpp-5.5.1/tools/macosx/share/cmake/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
      CMakeLists.txt:2 (project)
    
    
    CMake Error at /Users/chenjienan/omnetpp-5.5.1/tools/macosx/share/cmake/Modules/CMakeCompilerIdDetection.cmake:37 (cmake_parse_arguments):
      Unknown CMake command "cmake_parse_arguments".
    Call Stack (most recent call first):
      /Users/chenjienan/omnetpp-5.5.1/tools/macosx/share/cmake/Modules/CMakeDetermineCompilerId.cmake:128 (compiler_id_detection)
      /Users/chenjienan/omnetpp-5.5.1/tools/macosx/share/cmake/Modules/CMakeDetermineCompilerId.cmake:147 (CMAKE_DETERMINE_COMPILER_ID_WRITE)
      /Users/chenjienan/omnetpp-5.5.1/tools/macosx/share/cmake/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
      /Users/chenjienan/omnetpp-5.5.1/tools/macosx/share/cmake/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
      CMakeLists.txt:2 (project)
    
    
    CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
    Missing variable is:
    CMAKE_C_COMPILER_ENV_VAR
    CMake Error: Could not find cmake module file: /private/var/folders/m7/8x1_4t2x7214c99gxx01xtkm0000gn/T/pip-install-ggd5q25s/pycarl/build/temp.macosx-10.14-x86_64-3.7-version/CMakeFiles/3.3.2/CMakeCCompiler.cmake
    CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
    Missing variable is:
    CMAKE_CXX_COMPILER_ENV_VAR
    CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
    Missing variable is:
    CMAKE_CXX_COMPILER
    CMake Error: Could not find cmake module file: /private/var/folders/m7/8x1_4t2x7214c99gxx01xtkm0000gn/T/pip-install-ggd5q25s/pycarl/build/temp.macosx-10.14-x86_64-3.7-version/CMakeFiles/3.3.2/CMakeCXXCompiler.cmake
    CMake Error at CMakeLists.txt:2 (project):
      No CMAKE_CXX_COMPILER could be found.
    
      Tell CMake where to find the compiler by setting the CMake cache entry
      CMAKE_CXX_COMPILER to the full path to the compiler, or to the compiler
      name if it is in the PATH.
    
    
    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/m7/8x1_4t2x7214c99gxx01xtkm0000gn/T/pip-install-ggd5q25s/pycarl/setup.py", line 225, in <module>
        python_requires='>=3',
      File "/Users/chenjienan/stormpy/env/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/chenjienan/stormpy/env/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/m7/8x1_4t2x7214c99gxx01xtkm0000gn/T/pip-install-ggd5q25s/pycarl/setup.py", line 70, in run
        output = subprocess.check_output(['cmake', os.path.abspath("cmake")] + cmake_args, cwd=build_temp_version)
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/m7/8x1_4t2x7214c99gxx01xtkm0000gn/T/pip-install-ggd5q25s/pycarl/cmake']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/chenjienan/stormpy/env/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m7/8x1_4t2x7214c99gxx01xtkm0000gn/T/pip-install-ggd5q25s/pycarl/setup.py'"'"'; __file__='"'"'/private/var/folders/m7/8x1_4t2x7214c99gxx01xtkm0000gn/T/pip-install-ggd5q25s/pycarl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/m7/8x1_4t2x7214c99gxx01xtkm0000gn/T/pip-record-jdoz4rrp/install-record.txt --single-version-externally-managed --compile --install-headers /Users/chenjienan/stormpy/env/bin/../include/site/python3.7/pycarl Check the logs for full command output.

**Comment by volkm** [comment]
You are trying to install pycarl first, right? I recommend to install it manually (if not already done) with
`python3 setup.py develop`
For more information see [our documentation](https://moves-rwth.github.io/pycarl/installation.html#building-pycarl).

Additionally, it seems to me that the error comes from CMake and apparently CMake is taken from your folder `omnetpp-5.5.1`. I would have expected that CMake (as installed by Homebrew) is located somewhere in `/usr/local`. Maybe the wrong CMake is used?

**Comment by bblwbtd** [comment]
Thank you for your help! I removed the omnetpp-5.5.1 folder and reinstalled the cmake. And then, I built pycarl successfully. Unfortunately, when I am trying to build stormpy, it comes with new errors. Any ideas will be appreciated!

running develop
running egg_info
writing lib/stormpy.egg-info/PKG-INFO
writing dependency_links to lib/stormpy.egg-info/dependency_links.txt
writing requirements to lib/stormpy.egg-info/requires.txt
writing top-level names to lib/stormpy.egg-info/top_level.txt
reading manifest file 'lib/stormpy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'lib/stormpy.egg-info/SOURCES.txt'
running build_ext
Stormpy - Building into build/temp.macosx-10.14-x86_64-3.7
Stormpy - Using storm 1.4.1 from /usr/local/lib/cmake/storm
Stormpy - Support for DFTs found and included.
Stormpy - Support for parametric models found and included.
Stormpy - CMake args=['-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/chenjienan/stormpy/lib/stormpy/', '-DPYTHON_EXECUTABLE=/usr/local/opt/python/bin/python3.7', '-DCMAKE_BUILD_TYPE=Release', '-Dstorm_DIR=/usr/local/lib/cmake/storm', '-DHAVE_STORM_DFT=ON', '-DHAVE_STORM_PARS=ON']
-- pybind11 v2.2.dev0
-- STORM-DIR: /usr/local/lib/cmake/storm
-- STORM-INCLUDE-DIR: /usr/local/lib/cmake/storm/../../../include/storm
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20200221-5150-f7svmf/storm-1.4.1/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Traceback (most recent call last):
  File "setup.py", line 241, in <module>
    python_requires='>=3',
  File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
    self.install_for_development()
  File "/usr/local/lib/python3.7/site-packages/setuptools/command/develop.py", line 140, in install_for_development
    self.run_command('build_ext')
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 163, in run
    self.build_extension(ext, cmake_args, build_args)
  File "setup.py", line 197, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/Users/chenjienan/stormpy', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/chenjienan/stormpy/lib/stormpy/', '-DPYTHON_EXECUTABLE=/usr/local/opt/python/bin/python3.7', '-DCMAKE_BUILD_TYPE=Release', '-Dstorm_DIR=/usr/local/lib/cmake/storm', '-DHAVE_STORM_DFT=ON', '-DHAVE_STORM_PARS=ON']' returned non-zero exit status 1.

**Comment by volkm** [comment]
I think you have Storm installed via Homebrew, right? Currently the installation via Homebrew does not work with stormpy due to some issues with CMake. More information can be found in issue #12.

My suggestions is to [manually](http://www.stormchecker.org/documentation/obtain-storm/build.html) build Storm instead or to use one of the [Docker containers](http://www.stormchecker.org/documentation/obtain-storm/docker.html) which already contain [stormpy](https://hub.docker.com/r/movesrwth/stormpy/tags).
Sorry for the inconvenience.

**Comment by bblwbtd** [comment]
thanks for your help.
