### ISSUE TITLE
CTMC model building Failed

### ISSUE THREAD

**Issue by eshitazaman** [stormchecker/stormpy#17]
when I tried to build a CTMC model from the prism file of workstation cluster problem, I got the following error. Can you please help me to resolve it? where to put the flag '-pc'?
![Screen Shot 2020-07-16 at 8 31 20 PM](https://user-images.githubusercontent.com/45207632/87738723-a7617480-c7a3-11ea-87c7-79114beae5b2.png)

**Comment by sjunges** [comment]
Hi,

The following should work. 

stormpy.parse_program(model_file, prism_compat=True)

If it does not work, please reopen this issue.

Generally, some error messages are constructed for command line users. We will think about handing that differently.

**Comment by eshitazaman** [comment]
Hi Sebastian,

Thank you for your reply. I need your help for another issue, can you tell
me how I can use the parse_properties function with a formula string that
contains time parameter t (model checking CSL properties on CTMC model)?
For the current code, if I provide t in the formula it throws an error.

Thanks,
Eshita

**Comment by volkm** [comment]
Opened separate issue #18 for the second problem.
