### ISSUE TITLE
Installation on ununtu20.04 shows "storm version 1.6.2 not supported anymore"

### ISSUE THREAD

**Issue by wenchiyang** [stormchecker/stormpy#19]
I have followed the [instructions](https://moves-rwth.github.io/stormpy/installation.html#) to install storm ([build from source](https://www.stormchecker.org/documentation/obtain-storm/build.html)) and [pycarl](https://moves-rwth.github.io/pycarl/installation.html) on a ubuntu 20.04 machine. In the last step, while executing 

`python3 setup.py build_ext --storm-dir MY-PATH-TO-STORM develop`

I encountered the following error messages 

```
running build_ext
Stormpy - Building into build/temp.linux-x86_64-3.8
Stormpy - Error: Storm version 1.6.2 from MY-PATH-TO-STORM is not supported anymore!
```

Could the issue be related to that I am using ubuntu 20.04?

**Comment by volkm** [comment]
No, the problem does not come from Ubuntu 20.04.
You are using incompatible versions of Storm and stormpy. My guess is you are using the stable branch of Storm but the master branch of stormpy. These versions are not compatible. For more info see our [documentation](https://moves-rwth.github.io/stormpy/installation.html#compatibility-of-stormpy-and-storm).
The quickest fix is to use the [last release](https://github.com/moves-rwth/stormpy/releases/tag/1.6.2) of stormpy.

**Comment by sjunges** [comment]
Hi Wenchi,

I do not think that Ubuntu 20.04 is the problem. 
- Could you tell us the commit IDs for storm and stormpy that you used?
- Could you run storm from command line, i.e., run `MY-PATH-TO-STORM/bin/storm --version`

I suspect somehow a version mismatch. Could also be our logic, that has always been a bit iffy. Sorry for the inconvenience.

Best,
Sebastian

**Comment by wenchiyang** [comment]
Thank you for you fast replies! 
The issue was indeed that I was using the stable branch of Storm but the master branch of Stormpy. With the following commit IDs I could successfully build Stormpy. 

Storm (master): c12c0352f7f386ff45650f852bff0d6e48206ba8
Stormpy (master):dc94843aca90b3fcd9f1de779bd6bc700ae96fb1
