### ISSUE TITLE
pytest fails 

### ISSUE THREAD

**Issue by sjunges** [stormchecker/stormpy#2]
copied this from @cps-interactive in [storm issue 22](https://github.com/moves-rwth/storm/issues/22)

Hi, I got the following error message when running the test step after installing stormpy. I suspect that the error may have something to do the python version. My system is Mac OS X 10.13.4, which has a default Python version 2.7.14 and cannot be removed (as required by the system). But I have installed Python 3.6 separately. When I install strompy, I used "python3" command. However, the test session is using python 2.7.14. Is there a way to config stormpy and let python3 be the default version?

$ py.test tests/
============================= test session starts ==============================
platform darwin -- Python 2.7.14, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
rootdir: /Users/lf291/workspace/stormpy, inifile: setup.cfg
collected 0 items / 1 errors

==================================== ERRORS ====================================
______________________________ ERROR collecting _______________________________
/usr/local/lib/python2.7/site-packages/py/_path/common.py:377: in visit
for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
/usr/local/lib/python2.7/site-packages/py/_path/common.py:419: in gen
if p.check(dir=1) and (rec is None or rec(p))])
/usr/local/lib/python2.7/site-packages/_pytest/main.py:434: in _recurse
ihook = self.gethookproxy(path)
/usr/local/lib/python2.7/site-packages/_pytest/main.py:338: in gethookproxy
my_conftestmodules = pm._getconftestmodules(fspath)
/usr/local/lib/python2.7/site-packages/_pytest/config.py:348: in _getconftestmodules
mod = self._importconftest(conftestpath)
/usr/local/lib/python2.7/site-packages/_pytest/config.py:376: in _importconftest
raise ConftestImportFailure(conftestpath, sys.exc_info())
E ConftestImportFailure: ImportError('No module named stormpy._config',)
E File "/usr/local/lib/python2.7/site-packages/pytest/assertion/rewrite.py", line 213, in load_module
E py.builtin.exec(co, mod.dict)
E File "/usr/local/lib/python2.7/site-packages/py/builtin.py", line 221, in exec
E exec2(obj, globals, locals)
E File "", line 7, in exec2
E File "/Users/lf291/workspace/stormpy/tests/dft/conftest.py", line 1, in 
E from configurations import has_dft
E File "/Users/lf291/workspace/stormpy/tests/configurations.py", line 3, in 
E import stormpy._config as config
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.19 seconds ============================

**Comment by sjunges** [comment]
Hi,

thanks for your report. We will try to clarify the documentation in this regard.
 Indeed, the problem is that pytest as installed on your machine is defaulted to python2.

You can either run:
`python3 -m pytest 
`
but that might be inconvenient in the long run.

I guess that using virtual environments as mentioned in the [getting started](https://moves-rwth.github.io/stormpy/installation.html#requirements) is a bit more convenient.

Hope this helps,
Sebastian

**Comment by lf9u** [comment]
Hi Sebastian,

Thank you for your answer. Would this issue (Python3 vs. Python2) affect the general usage of stormpy other than the Pytest? 

Thanks
Lu

**Comment by volkm** [comment]
Hi,

as stormpy only works with python3 you should make sure to always use python3. We implemented an additional check for the right python version in da81f6cf1ab94ae0ef748550883a69cebb1d405c and throw an error if python2 is used.

As long as you run your scripts with pyhon3 you should encounter no problems.

However, to be on the safe side, we recommend to use virtual environments.
The following steps create a virtual environment for stormpy which uses python3 (see our updated [documentation](https://moves-rwth.github.io/stormpy/installation.html#virtual-environments)):
```
pip install virtualenv
virtualenv -p python3 env_stormpy
source env_stormpy/bin/activate
cd STORMPY_DIRECTORY
python setup.py develop
py.test tests/
```

Hope this helps
Matthias

**Comment by arincbulgur** [comment]
Hi, I got the following error message when running the test step. My system is Mac OS X 10.14.2. It has a default Python 3.6.5. I first made the installation with the available master branch of CArL. But, afterwards,  I removed the available CArL and reinstalled the master14 branch of CArL instead. I use the master14 branch for the installation of pycarl and storm. For the installation of STORM, Homebrew is preferred.

$ python3 -m pytest
============================= test session starts ==============================
platform darwin -- Python 3.6.5, pytest-3.5.1, py-1.5.3, pluggy-0.6.0
rootdir: /Users/arincbulgur/stormpy, inifile: setup.cfg
plugins: remotedata-0.2.1, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 0 items / 1 errors                                                   

==================================== ERRORS ====================================
______________________________ ERROR collecting  _______________________________
../anaconda3/lib/python3.6/site-packages/_pytest/config.py:334: in _getconftestmodules
    return self._path2confmods[path]
E   KeyError: local('/Users/arincbulgur/stormpy/tests/dft')

During handling of the above exception, another exception occurred:
../anaconda3/lib/python3.6/site-packages/_pytest/config.py:365: in _importconftest
    return self._conftestpath2mod[conftestpath]
E   KeyError: local('/Users/arincbulgur/stormpy/tests/dft/conftest.py')

During handling of the above exception, another exception occurred:
../anaconda3/lib/python3.6/site-packages/_pytest/config.py:371: in _importconftest
    mod = conftestpath.pyimport()
../anaconda3/lib/python3.6/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
../anaconda3/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
tests/dft/conftest.py:1: in <module>
    from configurations import has_dft
tests/configurations.py:3: in <module>
    import stormpy._config as config
E   ModuleNotFoundError: No module named 'stormpy'

During handling of the above exception, another exception occurred:
../anaconda3/lib/python3.6/site-packages/py/_path/common.py:377: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
../anaconda3/lib/python3.6/site-packages/py/_path/common.py:418: in gen
    dirs = self.optsort([p for p in entries
../anaconda3/lib/python3.6/site-packages/py/_path/common.py:419: in <listcomp>
    if p.check(dir=1) and (rec is None or rec(p))])
../anaconda3/lib/python3.6/site-packages/_pytest/main.py:434: in _recurse
    ihook = self.gethookproxy(path)
../anaconda3/lib/python3.6/site-packages/_pytest/main.py:338: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
../anaconda3/lib/python3.6/site-packages/_pytest/config.py:348: in _getconftestmodules
    mod = self._importconftest(conftestpath)
../anaconda3/lib/python3.6/site-packages/_pytest/config.py:376: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   _pytest.config.ConftestImportFailure: ModuleNotFoundError("No module named 'stormpy'",)
E     File "/Users/arincbulgur/anaconda3/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
E       py.builtin.exec_(co, mod.__dict__)
E     File "/Users/arincbulgur/stormpy/tests/dft/conftest.py", line 1, in <module>
E       from configurations import has_dft
E     File "/Users/arincbulgur/stormpy/tests/configurations.py", line 3, in <module>
E       import stormpy._config as config
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.30 seconds ============================

**Comment by sjunges** [comment]
The error message seems to indicate that you did not install stormpy..

Can you (if more convenient via mail) send us the steps you did to install stormpy?

**Comment by arincbulgur** [comment]
**I got the following during the installation of Stormpy:**

$ python3 setup.py develop
running develop
running egg_info
writing lib/stormpy.egg-info/PKG-INFO
writing dependency_links to lib/stormpy.egg-info/dependency_links.txt
writing requirements to lib/stormpy.egg-info/requires.txt
writing top-level names to lib/stormpy.egg-info/top_level.txt
reading manifest file 'lib/stormpy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'lib/stormpy.egg-info/SOURCES.txt'
running build_ext
Stormpy - Building into build/temp.macosx-10.7-x86_64-3.6
Stormpy - Using storm 1.3.0 from /usr/local/lib/cmake/storm
Stormpy - Support for DFTs found and included.
Stormpy - Support for parametric models found and included.
Stormpy - CMake args=['-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/arincbulgur/stormpy/lib/stormpy/', '-DPYTHON_EXECUTABLE=/Users/arincbulgur/anaconda3/bin/python3', '-DCMAKE_BUILD_TYPE=Release', '-Dstorm_DIR=/usr/local/lib/cmake/storm', '-DHAVE_STORM_DFT=ON', '-DHAVE_STORM_PARS=ON']
-- pybind11 v2.2.dev0
-- STORM-DIR: /usr/local/lib/cmake/storm
-- STORM-INCLUDE-DIR: /usr/local/lib/cmake/storm/../../../include/storm
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "storm" includes non-existent path

    "/tmp/stormchecker-20190124-86356-k1u53s/storm-1.3.0/resources/3rdparty/l3pp/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

**I had made the installation of Storm by Homebrew. I tried to rebuild the Storm from the source code and I got the following error:**

$ make
Scanning dependencies of target sylvan
[  0%] Creating directories for 'sylvan'
[  0%] No download step for 'sylvan'
[  0%] No patch step for 'sylvan'
[  0%] No update step for 'sylvan'
[  1%] Performing configure step for 'sylvan'
-- sylvan configure command succeeded.  See also /Users/arincbulgur/storm/build/sylvan/src/sylvan-stamp/sylvan-configure-*.log
[  1%] Performing build step for 'sylvan'
-- sylvan build command succeeded.  See also /Users/arincbulgur/storm/build/sylvan/src/sylvan-stamp/sylvan-build-*.log
[  1%] No install step for 'sylvan'
[  1%] Completed 'sylvan'
[  1%] Built target sylvan
Scanning dependencies of target cudd3
[  1%] Creating directories for 'cudd3'
[  1%] No download step for 'cudd3'
[  1%] Performing patch step for 'cudd3'
[  1%] No update step for 'cudd3'
[  1%] Performing configure step for 'cudd3'
CMake Error at /Users/arincbulgur/storm/build/resources/3rdparty/cudd-3.0.0/src/cudd3-stamp/cudd3-configure-RELEASE.cmake:16 (message):
  Command failed: 1

   '/Users/arincbulgur/storm/resources/3rdparty/cudd-3.0.0/configure' '--enable-shared' '--enable-obj' '--with-pic=yes' '--prefix=/Users/arincbulgur/storm/build/resources/3rdparty/cudd-3.0.0' '--libdir=/Users/arincbulgur/storm/build/resources/3rdparty/cudd-3.0.0/lib' 'CC=/Library/Developer/CommandLineTools/usr/bin/cc' 'CXX=/Library/Developer/CommandLineTools/usr/bin/c++'

  See also

    /Users/arincbulgur/storm/build/resources/3rdparty/cudd-3.0.0/src/cudd3-stamp/cudd3-configure-*.log


make[2]: *** [resources/3rdparty/cudd-3.0.0/src/cudd3-stamp/cudd3-configure] Error 1
make[1]: *** [CMakeFiles/cudd3.dir/all] Error 2
make: *** [all] Error 2
