### ISSUE TITLE
ModuleNotFoundError: No module named 'stormpy'

### ISSUE THREAD

**Issue by GavinRens** [stormchecker/stormpy#22]
Hello!

This is probably due to my lack of Python programming skills, but I thought it best to seek the answer here:

I installed stormpy in my home directory.
I ran

python3.8 setup.py test

resulting in

================== 341 passed, 1 skipped, 1 warning in 30.67s ==================

which implies to me that it is working.

Now, I have my Python project at PycharmProjects/ProjectName

But when I run my project code, I get

...
import stormpy
ModuleNotFoundError: No module named 'stormpy'

How do I get my project and its interpreter to see stormpy?

**Comment by volkm** [comment]
I transferred your issue to the stormpy repository. Please post issues related to stormpy here. That way we keep a better overview of all issues.

I guess you followed our guide and have created a virtual environment in which stormpy is installed. If you want to use stormpy from within Pycharm you need to use the same virtual environment. You can set it following [this guide](https://www.jetbrains.com/help/pycharm/creating-virtual-environment.html#existing-environment).

**Comment by GavinRens** [comment]
For the record:

Initially, I did not create a virtual environment. So, in order to let PyCharm see stormpy (as advised above), I re-installed it in a  virtual environment as described in the guide. But then the installation failed. Then I re-installed stormpy normally (not in a virtual environment) and got success. (Confirmed with python3.8 setup.py test)

Still getting

ModuleNotFoundError: No module named 'stormpy'

Could this be due to my project having its own virtual environment?:
![Screenshot 2020-12-04 at 13 35 22](https://user-images.githubusercontent.com/41202408/101164721-c919a600-3635-11eb-8b62-51d9aea37c49.png)

**Comment by volkm** [comment]
Yes, if you are using a different virtual environment in pycharm, stormpy is not installed in this environment. You need to install stormpy into that environment as well and it should be available from within Pycharm. If you encounter any concrete errors, let us know and we will take a look into it.

**Comment by GavinRens** [comment]
Finally,

(Regular) storm was installed (built from source) in my home directory.
stormpy was installed by running the following commands in the Terminal pane of my PyCharm project (which uses venv). That is, from the top level project directory:

$ git clone https://github.com/moves-rwth/stormpy.git
$ cd stormpy
$ pip install -ve .

To be clear, a "stormpy" directory ends up inside the project.
