### ISSUE TITLE
Looking for alternate datatype for 'value' in SparseMatrixEntry

### ISSUE THREAD

**Issue by oyendrila-dobe** [stormchecker/stormpy#26]
Is there a way to represent the transition probabilities in the Sparse matrix as fractions instead of float values? The float number generate impreciseness when comparing the same fraction with the generated float variable. For e.g., (1/6) is stored as (8333333333333333/50000000000000000), which when compared with (1/6) returned false.

**Comment by sjunges** [comment]
storm::RationalNumber is what you are looking for, on the C++ side.

For stormpy, that means all the Models/Data types with "Exact" in them.

**Comment by oyendrila-dobe** [comment]
So essentially I need to generate a new Exact Sparse matrix from the current Sparse transition matrix and utilize it as the transition matrix henceforth.

**Comment by oyendrila-dobe** [comment]
Installed stormpy 1.6.3, but cannot find ExactSparseMatrix class in storage. Can you suggest a work-around?

**Comment by oyendrila-dobe** [comment]
Rebuilding the library solved the issue. Thank you.
