### ISSUE TITLE
Parsing PRISM Model to get all Labels

### ISSUE THREAD

**Issue by ribsthakkar** [stormchecker/stormpy#29]
The storm cli allows the command: `storm --prism result.txt --buildfull --prop "Pmax=? [F \"goal\"]"` when I want to build the full model with all state labels even though the labels might not be used in the properties.
However, in stormpy, I am not able to find an option to parse all of the labels from the same `result.txt` prism model definition.

Is there any way to find or enable that option?
I initially assumed the simplify argument affected the parsing, but I didn't see anything different in my results:
`    prism_program = stormpy.parse_prism_program("result.txt", simplify=False)`

This is a snippet of my code for what I am doing:
```
 prism_program = stormpy.parse_prism_program("result.txt")
    formula_str = "Pmax=? [F \"goal\"]"
    properties = stormpy.parse_properties(formula_str, prism_program)
    model = stormpy.build_model(prism_program, properties)
    result = stormpy.model_checking(model, formulas[0], extract_scheduler=True)
    initial_state = mdp.initial_states[0]
    scheduler = result.scheduler
    for state in model.states:
        choice = scheduler.get_choice(state)
        action = choice.get_deterministic_choice()
        print(model.labels_state(state), state.actions[action])
```
Here is the output (notice how the only states that are labeled are the deadlock, goal, and init states):
```
{'init'} 2
set() 2
set() 3
set() 2
set() 2
set() 0
set() 0
set() 2
set() 2
set() 2
set() 2
{'goal'} 0
set() 0
set() 0
set() 0
set() 3
set() 2
set() 0
{'goal'} 0
set() 0
set() 2
set() 0
set() 2
{'goal'} 0
set() 0
set() 2
set() 0
set() 0
set() 0
set() 0
set() 0
set() 0
{'goal'} 0
{'deadlock'} 0
{'deadlock'} 0
{'deadlock'} 0
{'deadlock'} 0
{'deadlock'} 0
{'deadlock'} 0
{'deadlock'} 0
{'deadlock'} 0
```
Along the same lines, how can we get the choice label names as well?

**Comment by volkm** [comment]
If you don't provide  any properties to the build function, then all labels are preserved:
```
model = stormpy.build_model(prism_program)
```

You can explicitly configure how to build a model in stormpy by using the `BuilderOptions` (see the auto-generated [documentation](https://moves-rwth.github.io/stormpy/api/core.html#stormpy.BuilderOptions)).
To build the choice labels, you can do the following:
```
options = stormpy.BuilderOptions()
options.set_build_all_labels()
options.set_build_choice_labels()
model = stormpy.build_sparse_model_with_options(prism_program, options)
```

Obtaining the choice labels from the scheduler is not nicely implemented at the moment. This workaround should give you the desired output though:
```
scheduler = result.scheduler
assert model.has_choice_labeling()
choice_labeling = model.choice_labeling
row_group_indices = model.transition_matrix._row_group_indices
for state in model.states:
    choice = scheduler.get_choice(state)
    action = choice.get_deterministic_choice()
    choice_label = choice_labeling.get_labels_of_choice(row_group_indices[state.id])
    print(state, model.labels_state(state), state.actions[action], choice_label)
```

**Comment by ribsthakkar** [comment]
Ah thank you, that did the trick!
