### ISSUE TITLE
Scheduler extraction inconsistencies

### ISSUE THREAD

**Issue by MaximeBouton** [stormchecker/stormpy#3]
Hello, 
I am trying to use the `extract_scheduler` option on a simple MDP but I am unable to retrieve the scheduler for certain properties. 

My problem has 101 states, and two labels "bad" and "good", two states are labeled "bad", one state is labeled "good".
Am I doing something wrong when writing the properties? 

Following are two examples, one breaking and one working for the same MDP model with different properties. In both cases, `result` contains a numerical value for each state (that seems good), but it does not contain the scheduler.

Breaking example:
```python
import stormpy

tra_file = "grid_world.tra"
lab_file = "grid_world.lab"
model = stormpy.build_sparse_model_from_explicit(tra_file, lab_file)

property = "Pmax=? [ ! \"bad\" U<=30 \"good\"]"
# property = "Pmax=? [ G ! \"bad\"]" # breaks as well
# property = "Pmax=? [F<=30 \"good\"]"  # breaks as well

properties = stormpy.parse_properties(property)

result = stormpy.model_checking(model, properties[0], extract_scheduler=True)
assert result.has_scheduler
```
Working example:
```python
import stormpy

tra_file = "grid_world.tra"
lab_file = "grid_world.lab"
model = stormpy.build_sparse_model_from_explicit(tra_file, lab_file)

property = "Pmax=? [ ! \"bad\" U \"good\"]"
# property = "Pmax=? [F \"good\"]" # works as well

properties = stormpy.parse_properties(property)

result = stormpy.model_checking(model, properties[0], extract_scheduler=True)
assert result.has_scheduler
```

Platform:
Windows Subsystem for Linux - Ubuntu 16.04
Storm version: Storm 1.2.2-alpha (dev)
Stormpy: installed from master branch
Python 3.6.5 Anaconda

**Comment by sjunges** [comment]
Thanks for your bug report. The problem might be due to the slightly more involved constraints. 
We will investigate this, but probably only after the upcoming weekend.

**Comment by MaximeBouton** [comment]
Thanks for the reply, do you have any idea if it is a stormpy related issue or storm? Is there a way to export the scheduler via a storm command directly?

**Comment by sjunges** [comment]
Hi Maxime,

sorry for the delay. Storm only supports the extraction for unbounded reachability. Feel free to open a feature request discussion in the storm repo.

Best,
Sebastian

P.S. Of course, some way of checking whether scheduler extraction is supported for a property would be good.

**Comment by MaximeBouton** [comment]
Thanks for the reply, I opened an issue in the storm repo:
moves-rwth/storm#23

**Comment by sjunges** [comment]
As this is currently not possible in storm, stormpy will not be able to support this.
