### ISSUE TITLE
MDP Transition Rewards

### ISSUE THREAD

**Issue by ribsthakkar** [stormchecker/stormpy#30]
Is there documentation or examples showing how we can define transition rewards for an MDP? And does Storm/Stormpy support models with negative rewards?

**Comment by volkm** [comment]
There is a small example in our [documenation](https://moves-rwth.github.io/stormpy/doc/models/building_mdps.html#Reward-models) on how to define state-action rewards for MDPs. For transition rewards, you can use the same method but set the `optional_transition_reward_matrix` in the constructor instead. You can of course also directly define the rewards in your input file (Prism/Jani/Explicit input).

To the best of my knowledge, we do not support models with negative rewards at the moment.

**Comment by ribsthakkar** [comment]
Ok I see, I assume I'd use the sparse matrix builder in the same way to define the transition rewards as it was for the transition matrix.

**Comment by volkm** [comment]
Yes, you can use the sparse matrix builder for this as well.
