### ISSUE TITLE
Error building stormpy

### ISSUE THREAD

**Issue by agausen** [stormchecker/stormpy#33]
Hello,

I keep getting an error when trying to build stormpy. I have:
- manually installed storm
- installed carl and pycarl

I am using the following command:
`python3 setup develop`

Error message (image of full logs below):
```
 [20%] Building CXX object CMakeFiles/pars.dir/src/pars/pla.cpp.o
/path/to/stormpy/src/pars/pla.cpp:86:24: error: no matching function for call
      to 'parseRegion'
                return storm::api::parseRegion<storm::RationalFunction>(regionString, variables, splittingThreshold);
```

Please could you advise me how to continue?

<img width="848" alt="Screenshot 2021-02-26 at 09 46 17" src="https://user-images.githubusercontent.com/72968435/109284239-8e2fa480-7817-11eb-8906-06d4b5db4c5b.png">

**Comment by tquatmann** [comment]
Hi,
it seems like the versions of `storm` and `stormpy` that you use are not compatible with each other. Can you check out the most recent release `1.6.3` (using `git checkout 1.6.3`) for both and try again?

**Comment by agausen** [comment]
Thank you so much for your quick response! Its working now!
