### ISSUE TITLE
Statistical model checking

### ISSUE THREAD

**Issue by huypn12** [stormchecker/stormpy#34]
It is very nice that Stormpy support discrete event simulation as I have seen in the simulator example with mdp and dtmc. However, I would like to ask if Stormpy also support some steps of statistical model checking, for example verifying if a simulated trace in a dtmc model satisfies a pctl property of interest. 
Thank you Stormpy team.

**Comment by sjunges** [comment]
Hi, 

sorry for the slow response. We do not support statistical model checking.

Sebastian
