### ISSUE TITLE
Uncertain Discrete-time Markov chain

### ISSUE THREAD

**Issue by nielsneerhoff** [stormchecker/stormpy#35]
Hello Stormpy team,

Having fun with your library so far. Thanks for sharing!

I am trying to build an uncertain Discrete-time Markov chain from scratch using Storm(py). The constraints on the transition parameters are values representing a lower and upper bound on the transition probability. I have thus far represented these lower and upper bounds by two (sparse) transition matrices. These matrices follow as output from another element in the model-checking pipeline.

In the Stormpy documentation, I see 3 small examples on how to instantiate, investigate and check a parametric model. I also see functionality to read in a parametric model from a symbolic description (e.g. PRISM).

Is there also a way to build a parametric model from scratch, e.g. with the SparseMatrixBuilder, or by providing the entire (lower and upper bound) transition matrix? And how can I check a property of a DTMC of which the transition probabilities are not just entirely unknown parameters, but parameters between a lower and upper bound?

Thanks a lot in advance,
Niels

**Comment by sjunges** [comment]
Hi Niels,

good to hear that you enjoy it. The python bindings remain an academic prototype and a moving target.

Before I can answer your question, I will try to understand slightly better what exactly you have in mind. After all, depending on what you want to analyse, we may need to handle things differently. 

First, parametric models include but are more powerful than interval (uncertain) models. Sadly, storm so far has no direct support for interval-based models, but in many cases, we can get around quite well by using the more powerful parametric models or using, as you suggested, two transition matrices.  So one question would be whether you really want parametric models or interval-based models, and if you want interval-based models, and then it depends a bit a bit on your goals how to do this best. 

The second question is about checking parametric DTMCs. For an MC, you can talk about 'the' probability, but for a parametric or uncertain model, that is of course a bit more involved. Do you want to know if 'for all' parameter values, a probability is above a threshold, or whether there 'exists' a parameter value such that your probability is above a threshold, or do you want to find a parameter value that maximises the probability? 

Sorry for responding to your question with questions.  If you feel uncomfortable answering these questions publicly, you can reach out by email!

Best,
Sebastian

**Comment by nielsneerhoff** [comment]
Hi Sebastian,

Thanks for your quick reply and your questions! As this is about work that is still unfinished I will send you a private mail and close this issue.
