### ISSUE TITLE
Error when using stormpy with multiprocessing

### ISSUE THREAD

**Issue by huypn12** [stormchecker/stormpy#36]
Hi stormpy team,

I am trying to speed up my project using python multiprocessing. However, it turns out that it is not possible due to stormpy's components are unable to be pickled. For example, with this simple test of multiprocessing using the stormpy 01_simulation example [test_parallel](https://raw.githubusercontent.com/huypn12/bbeess-py/main/tests/test_parallel.py)

I got the following error:
![image](https://user-images.githubusercontent.com/2792821/112452364-d8447100-8d56-11eb-9385-d8f3b6ae1de9.png)

I tried [pathos.multiprocessing](https://pypi.org/project/pathos/), which uses more advanced serializer [dill](https://pypi.org/project/dill/),  but still dill cannot serialize stormpy classes.

Environment:
Opensuse 15.2, pyenv python 3.8.8

**Comment by sjunges** [comment]
Hi,

our code is written in C++, and those classes do generally not support serialisation, so it is very unlikely that we can support those operations. To the very least, they would require a major implementation effort. We had some success with explicitly running multiple threads, but I can also not guarantee that all our classes are thread safe.

Best,
Sebastian
