### ISSUE TITLE
Python 3.7 seems unsupported

### ISSUE THREAD

**Issue by jjguijt** [stormchecker/stormpy#4]
I'm using Ubuntu 19.04 with default Python3.7 installed. I'm trying to install stormpy through pip.

A part of the error message:
.venv/include/python3.7m/pythread.h:98:20: note: declared here
   PyAPI_FUNC(void *) PyThread_get_key_value(int key) Py_DEPRECATED(3.7);

It may be related to pybind11, since it appears in the traceback.

If you need more info to reproduce/pinpoint the problem then please let me know!

**Comment by volkm** [comment]
The installation via pip is a quite new feature, but I am happy you are using it already.
Can you give us the complete output of the installation step to pinpoint the problem? If you add the ``-v`` flag to the pip command you should get a verbose output with more debug messages.

**Comment by jjguijt** [comment]
On my main machine I got it working by using Python 3.6, but when I wanted to reproduce my earlier troubles in a container with Python 3.7 I couldn't. I'll probably have had a mix-up with some dependencies that caused my installation to fail, but running Python 3.7 wasn't the problem.

However, I do have some log file with a lot of warnings about pybind11, I'll send that to your RWTH Aachen email address.

**Comment by oyendrila-dobe** [comment]
I think I have found the example he was talking about. I'm trying to install stormpy on a docker with ubuntu 19.06.
<img width="1410" alt="Screen Shot 2019-09-24 at 7 30 52 PM" src="https://user-images.githubusercontent.com/14862450/65559848-f3d08080-df01-11e9-8ad3-064532c15cb7.png">
