### ISSUE TITLE
PRISM Model State enumeration vs Stormpy State enumeration

### ISSUE THREAD

**Issue by ribsthakkar** [stormchecker/stormpy#42]
Does the Storm enumeration of states match that of the PRISM model? In other words, does the exported state enumeration from PRISM looks like this:
```
(x,y,t,k_S_M,s_S_M,k_S_G,s_S_G,k_S_D,s_S_D,e,o)
0:(1,1,1,0,2,1,2,2,2,false,false)
1:(1,1,2,0,2,1,2,2,2,false,false)
2:(1,1,3,0,2,1,2,2,2,false,false)
3:(1,1,3,0,2,1,2,2,4,false,true)
```
Does state 3 in the exported PRISM file match the same state variables when the prism file is parsed by Storm? 

The reason I am asking is so that when I use the scheduler produced by model checking Storm says to choose action 0 in state 3, I can say in state=(1,1,3,0,2,1,2,2,4,false,true), choose Action A?

If that is not the case, how can this be resolved or are there workarounds for this outside of labeling every unique state and having storm parse those labels? Labeling every unique state is easy when we have 100s of states, but when I reached the order of 1000s-1000000s, it breaks down PRISM's parsing ability.

**Comment by ribsthakkar** [comment]
Ok so I realized through some trial and error that the state enumerations are not preserved. 
So, this leaves me with a question of how I can determine the possible state numbers for a given action/choice and the values of the variables in the model definition for those given states without creating a label for every possible state in my prism model file?
@volkm @sjunges

**Comment by tquatmann** [comment]
I can confirm that the order is not the same as in PRISM.
What you looking for is something we call **state valuations**. I think [this](https://github.com/moves-rwth/stormpy/blob/b13e84298617dfaf6bcaba18372b7a3c3dfe1b60/examples/analysis/04-analysis.py) example should get you started.

Also note that a similar problem arises with the ordering of the actions, i.e., action `0` might not be what you think it is and you would want either the **choice labels** (which for PRISM models should be the label you put in square brackets at the beginning of each command) or the **choice origins** (which unambiguously represents the set of commands that generated this action (aka choice)).

Unfortunately, there is no example using `choice_labels` and/or `choice_origins` but it is very similar to state valuations. Please comment here if you need further help in this regard.

**Comment by ribsthakkar** [comment]
Thanks for the reference. With that, I was able to get the state valuations for each state ID. To determine the choice labels, I was making one key assumption which was that the deterministic action returned by the scheduler was the offset from the row_group_start of the state ID. Then I use the choice labeling to extract the label of the choice. Is this correct?
Snippet describes usage of my assumption below:
```
 for state in model.states:
        state_valuation = json.loads(model.state_valuations.get_json(state.id))
        action = scheduler.get_choice(state).get_deterministic_choice()
        optimal_action = model.transition_matrix.get_row_group_start(state.id) + action
        print(f"Choose {choice_labeling.get_labels_of_choice(optimal_action).pop()} in state {state_valuation}")
```

**Comment by ribsthakkar** [comment]
Also it seems like solving a PRISM model in Storm vs running PRISM natively drastically varies in performance. A model that takes 2 minutes to solve and export with PRISM natively is currently taking upwards of 2.5 hours ( ....and still running) when using Storm to run. Granted there are several variables and some complexity in the properties, but the overall size according to PRISM is about 3 million states. It also seems like Storm is not making use of all of the RAM and cores. Is there some resource limit I need to configure when using Storm?

**Comment by tquatmann** [comment]
Yes, your assumption is right and your code looks good as far as I can see. I'm just not sure if the `pop()` has any weird side effects as it changes the set (which is probably not your intent here).

The performance issue you mentioned is a bit odd. Usually, models with ~3 million states can be built much faster than that. Is it possible to send the model to me ([privately](mailto:tim.quatmann@cs.rwth-aachen.de) if you prefer ) so I can have a further look at what is going on?

**Comment by ribsthakkar** [comment]
The `pop()` call was just to extract the element from the set. After extracting the scheduler, I also no-longer make use of the model in case it does modify the original data structure. 

I can share the model directly to your email.

**Comment by tquatmann** [comment]
In a nutshell, the performance differences between Storm and PRISM happen due to the way they represent the model by default: Storm's default uses an explicit enumeration of the transitions whereas PRISM uses BDDs.

It happens to be the case that BDDs are much faster for your model. You can also use BDDs with Storm and Stormpy which can answer the query equally fast. However, the adversary export is currently not implemented for BDD-based representations.

I'll reach to you privately to provide a few more insights (which are more specific to your model).
