### ISSUE TITLE
Stormpy model interface

### ISSUE THREAD

**Issue by cazevedo** [stormchecker/stormpy#5]
Hello,
I was trying to interface stormpy with my python code, and was wondering if we need to write a prism file every time we want to run our model in storm or if there is some python object that we can instantiate and input it directly to storm?
I mean, I'm considering that constructing that model would be a computationally more efficient way of doing it.

**Comment by sjunges** [comment]
Hi Carlos,

if you already have an explicit representation of the model, it would be better to put that into storm(py) directly. 
Both main contributors to stormpy are currently on a break, so we may take a bit of time before we can help you. 

(The bindings for matrices are in place, but the constructors for Markov chains are missing).

**Comment by volkm** [comment]
It took a complete year, but we have finally support for explicitly creating models in the latest version of stormpy.
One has to create all necessary components of a model - transition matrix, labeling, reward structures, etc. - and can then create a sparse model from these components.
To get started look into the documentation we provide for all model types on our [website](https://moves-rwth.github.io/stormpy/doc/models/building_dtmcs.html).
